### ISSUE TITLE
[Bug]: Parquet File Output fails in Hop 2.16.0 with NoClassDefFoundError (worked in 2.15.0)

### ISSUE THREAD

**Issue by AhmAmri** [apache/hop#6148]
### Apache Hop version?

2.16.0

### Java version?

17.0.17

### Operating system

Docker

### What happened?

When upgrading from Apache Hop 2.15.0 to Apache Hop 2.16.0, the Parquet File Output transform stops working.
The same pipeline and configuration that previously worked now fails with a NoClassDefFoundError related to a missing Woodstox class:
com.ctc.wstx.io.InputBootstrapper.

This seems to be a dependency regression, the Parquet output transform requires a Woodstox/WSTX XML parser class that is no longer available in the classpath in version 2.16.0.

**Environment**

Hop version: 1.16.0

Working version: 2.15.0
Execution mode: Hop Web / Docker
Transform: Parquet File Output

**Steps to Reproduce**

Create a pipeline using Parquet File Output
Run the pipeline on Hop 2.16.0
Observe that Hop fails when trying to write the parquet file

**Error logs:** 
ERROR: Unexpected error
ERROR: java.lang.NoClassDefFoundError: com/ctc/wstx/io/InputBootstrapper
    at org.apache.hop.parquet.transforms.output.ParquetOutput.openNewFile(ParquetOutput.java:135)
    at org.apache.hop.parquet.transforms.output.ParquetOutput.processRow(ParquetOutput.java:100)
    at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:54)
    at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: com.ctc.wstx.io.InputBootstrapper
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1377)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1186)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Web
